name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

env:
  TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  ci:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    defaults:
      run:
        working-directory: '.'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:latest
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v3
      - name: Install Tinybird CLI
        run: curl https://tinybird.co | sh
      - name: Add PostgreSQL host & port
        run: tb secret set STG_PG_HOST_PORT ${{ secrets.STG_PG_HOST_PORT }}
      - name: Add PostgreSQL database
        run: tb secret set STG_PG_DB ${{ secrets.STG_PG_DB }}
      - name: Add PostgreSQL username
        run: tb secret set STG_PG_USERNAME ${{ secrets.STG_PG_USERNAME }}
      - name: Add PostgreSQL password
        run: tb secret set STG_PG_PASSWORD ${{ secrets.STG_PG_PASSWORD }}
      - name: Build project
        run: tb build
      - name: Check secrets
        run: tb secret ls
      - name: Deployment check
        run: tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deploy --check
